module Fem

export SubDomain

export do_isotropic_elliptic_assembly
export update_isotropic_elliptic_assembly!
export get_mass_matrix

export get_dirichlet_inds
export apply_dirichlet
export append_bc

export do_mass_covariance_assembly
export solve_kl

export get_mesh
export save_mesh
export load_mesh
export mesh_partition
export save_partition
export load_partition
export get_total_area

export set_subdomain
export set_subdomains

export prepare_global_schur
export prepare_local_schurs
export apply_global_schur
export apply_local_schur
export apply_local_schurs
export assemble_local_schurs
export apply_neumann_neumann_schur
export NeumannNeumannSchurPreconditioner
export prepare_neumann_neumann_schur_precond
export apply_neumann_neumann_induced
export NeumannNeumannInducedPreconditioner
export prepare_neumann_neumann_induced_precond
export apply_domain_decomposition_low_rank
export DomainDecompositionLowRankPreconditioner
export prepare_domain_decomposition_low_rank_precond
export apply_inv_a0, apply_inv_a0!, apply_hmat
export apply_lorasc
export LorascPreconditioner
export prepare_lorasc_precond
export get_schur_rhs
export get_subdomain_solutions
export merge_subdomain_solutions
export assemble_A_ΓΓ_from_local_blocks

export do_local_mass_covariance_assembly
export do_local_mass_assembly
export do_global_mass_reduced_assembly
export do_global_mass_covariance_reduced_assembly
export solve_local_kl
export solve_global_reduced_kl
export project_on_mesh
export draw
export draw!
export trim_and_order
export get_kl_coordinates

export pll_do_global_mass_covariance_reduced_assembly
export pll_solve_local_kl
export pll_draw

export suggest_parameters
export get_root_filename

export prepare_mc_sampler
export prepare_mcmc_sampler

include("Mesh.jl")
include("EllipticPde.jl")
include("BoundaryConditions.jl")
include("EllipticPdeDomainDecomposition.jl")
include("KarhunenLoeve.jl")
include("KarhunenLoeveDomainDecomposition.jl")
include("KarhunenLoevePllDomainDecomposition.jl")
include("KarhunenLoeveDomainDecompositionHelper.jl")
include("Samplers.jl")
end